### ISSUE TITLE
Tesselization

### ISSUE THREAD

**Issue by guillaume-florent** [guillaume-florent/standard-cad-parts#10]
The standard cad parts library should provide a way to access the tesselized representation of library parts.

**Comment by tpaviot** [comment]
I think this issue is duplicated with #12

**Comment by guillaume-florent** [comment]
Yes and no. Issue #12 mentions outputs that will use tesselization. The goal of this issue is to somehow store the results of a generic tesselization for performance reasons.

**Comment by guillaume-florent** [comment]
You were right. Tesselization is probably best stored in each format (STL, x3d ...) than from an arbitrary source and then converted.
