### ISSUE TITLE
Generators cannot contain comments or backslashes

### ISSUE THREAD

**Issue by guillaume-florent** [guillaume-florent/standard-cad-parts#11]
The code from generators cannot contain comments or backslashes (cut a long line) as their presence in the json file creates json standard compliance problems.

**Comment by tpaviot** [comment]
You mean the # character cannot be handled by a string in json ?

**Comment by guillaume-florent** [comment]
The # character is okay. Docstring characters were more problematic and """ have been converted to ''' for JSON storage. The eventual backslash (most often a Python line break for our usage) coming for generator code is now escaped in the JSON.
