### ISSUE TITLE
Generate STEP, x3dom and WebGL files

### ISSUE THREAD

**Issue by guillaume-florent** [guillaume-florent/standard-cad-parts#12]
The parts should be represented in various formats (STEP, x3dom, WebGL) using the JSON data as the unique point of truth.

**Comment by tpaviot** [comment]
@guillaume-florent This is what I suggested, but I wonder if this has to be done. Indeed STEP and Webgl files will require a lot of disk space, the size of the repository will quickly explode. Maybe it's not such a good idea. But we must provide a way, for the end-user, to generate the STEP export and webgl visualization on its own machine.

**Comment by guillaume-florent** [comment]
https://github.com/guillaume-florent/party offers an optional way to generate these files.
