### ISSUE TITLE
There should only one generate.py file that handles every sub-library in a similar way

### ISSUE THREAD

**Issue by guillaume-florent** [guillaume-florent/standard-cad-parts#13]
Currently, for prototyping, there is one generate.py file per sub-library. There should be only one generate.py at the root of the project.

**Comment by tpaviot** [comment]
@guillaume-florent the folder structure could be as follows:

root_folder
root_folder/catalog_manager_src
root_folder/catalog_manager_src/generate.py
root_folder/catalog_manager_src/templating.py
root_folder/catalogs
root_folder/catalogs/fasteners/screws
root_folder/catalogs/fasteners/screws/DIN912/generative_models
root_folder/catalogs/fasteners/screws/ISOblabla/generative_models
root_folder/catalogs/ball_bearings

**Comment by tpaviot** [comment]
There could also be two different generation scripts:

* the first one, generate-catalog.py taks a json catalog file as a parameter, for instance:

```
$ python generate-catalog.py dc_motor.json
```

* another one, generate-all-catalogs, that looks into all catalogs subfolders and generate libraries. It could be useful for testing (i.e. ensure all libraries can be generated) and check for regressions. For instance:

```
$ python generate-all-catalogs.py
```

**Comment by guillaume-florent** [comment]
@tpaviot I was also thinking that at some point we should separate the data in the JSONs from the code that handles it: catalogs and catalog_manager_src or similar is fine with me. I will implement that. The question of where to place a script that automates the creation of a library.json file remains open. I think it belongs to the catalog (i.e. not to the catalog manager) but we may discuss that.
