### ISSUE TITLE
Test script files after generation

### ISSUE THREAD

**Issue by tpaviot** [guillaume-florent/standard-cad-parts#15]
After the generation is achieved, the generated scripts should be tested, that is to say the python script has to be run.

Two ways to proceed IMO:

* generate/run a "test_scripts.py" which imports all generated modules, i.e.
```
import 608ZZ
import 624ZZ
import F63800ZZ
etc.
```
and then
```
$ python test_scripts.py
```
from a subprocess, get the output

or 

* create a list of all scripts:
```
scripts = ['608ZZ', '624ZZ', etc.]
```
loop over this list, and call
```
$ python -m "import 608ZZ"
$ python -m "import "624ZZ"
etc.
```
from a subprocess.

This 2nd solution has the advantage that is can be multithreaded, and we prevent memory overlaps between tests.

**Comment by guillaume-florent** [comment]
How about imp.load_source (or its PY3 equivalent) and retrieving all the folders named scripts in the file/folder hierarchy? No need to maintain a list of scripts to test. This still can be multithreaded and will catch potential errors in the scripts.

Pseudocode:
-------------
for each folder in os.walk():
    if folder_name is 'scripts':
        for each file in scripts:
            mod = imp.load_source(file)
            assert mod.part is not None
            assert mod.anchors is not None
            assert type(anchors) is tuple

**Comment by guillaume-florent** [comment]
tests/test_generated_scripts.py contains an implementation proposal of the generated scripts testing

**Comment by guillaume-florent** [comment]
The test breaks due to the metric screws library not being properly implemented yet.
