### ISSUE TITLE
Querying part libraries

### ISSUE THREAD

**Issue by tpaviot** [guillaume-florent/standard-cad-parts#25]
We must find a way to query the catalogs, so that the user can for instance choose "a screw with a diameter of 8mm and a length less than 50mm".

The content of the libraries is sotred in json files, so far I found the following tools able to browse/query a json content:

* ObjectPath, http://objectpath.org/, a query language for semi structured data ;

* TinyDb, a small/pure python document oriented database (similar to MongoDb) https://github.com/msiemens/tinydb

**Comment by guillaume-florent** [comment]
Issue moved to https://github.com/guillaume-florent/party
