### ISSUE TITLE
Rules field

### ISSUE THREAD

**Issue by guillaume-florent** [guillaume-florent/standard-cad-parts#9]
The library json file should contain a "Rules" field to allow automated checks of the library data quality.

**Comment by tpaviot** [comment]
Yes, this is related to the catalog quality. I suggest to create a "Quality" label, in the issue tracker.

**Comment by guillaume-florent** [comment]
A Quality label has been added to the issue tracker

**Comment by guillaume-florent** [comment]
rules_checking.py contains a check_library_json(json_filename) function that checks each data entry against rules defined in the 'rules' field.
